name: Welcome First PR

on:
  pull_request:
    types: [opened]

permissions:
  pull-requests: write
  issues: write # Thêm quyền issues để an toàn nếu action check quyền

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - name: Welcome First-time Contributor
        uses: actions/first-interaction@v3
        with:
          
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          
          # Nội dung comment cho PR
          pr_message: |
            Xin chào! Cảm ơn bạn đã gửi Pull Request đầu tiên cho dự án.
            

          
          # SỬA LỖI: Action yêu cầu phải có cả issue_message 
          issue_message: |
            Chào mừng bạn đến với dự án! Cảm ơn bạn đã mở Issue đầu tiên.